FROM public.ecr.aws/lambda/python:3.12

# Copy requirements.txt
COPY requirements.txt ${LAMBDA_TASK_ROOT}

# Install the specified packages
RUN pip install -r requirements.txt

COPY models ${LAMBDA_TASK_ROOT}/models
COPY src ${LAMBDA_TASK_ROOT}/src
COPY update_flights.py ${LAMBDA_TASK_ROOT}

# Set the CMD to your handler.
CMD [ "update_flights.handler" ]